// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { DelegationManager$Type } from "./DelegationManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["DelegationManager"]: DelegationManager$Type;
    ["contracts/DelegationManager.sol:DelegationManager"]: DelegationManager$Type;
  }

  interface ContractTypesMap {
    ["DelegationManager"]: GetContractReturnType<DelegationManager$Type["abi"]>;
    ["contracts/DelegationManager.sol:DelegationManager"]: GetContractReturnType<DelegationManager$Type["abi"]>;
  }
}
