/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CounterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "batchAdd"
      | "batchSubtract"
      | "divide"
      | "getCount"
      | "getMaxCount"
      | "multiply"
      | "owner"
      | "renounceOwnership"
      | "reset"
      | "setMaxCount"
      | "subtract"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountChanged"
      | "MaxCountUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "add", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "batchAdd",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSubtract",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "divide",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getMaxCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiply",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subtract",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchAdd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSubtract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "divide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMaxCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subtract", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CountChangedEvent {
  export type InputTuple = [
    newCount: BigNumberish,
    operation: string,
    value: BigNumberish
  ];
  export type OutputTuple = [
    newCount: bigint,
    operation: string,
    value: bigint
  ];
  export interface OutputObject {
    newCount: bigint;
    operation: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxCountUpdatedEvent {
  export type InputTuple = [newMaxCount: BigNumberish];
  export type OutputTuple = [newMaxCount: bigint];
  export interface OutputObject {
    newMaxCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Counter extends BaseContract {
  connect(runner?: ContractRunner | null): Counter;
  waitForDeployment(): Promise<this>;

  interface: CounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  batchAdd: TypedContractMethod<[values: BigNumberish[]], [void], "nonpayable">;

  batchSubtract: TypedContractMethod<
    [values: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  divide: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  getCount: TypedContractMethod<[], [bigint], "view">;

  getMaxCount: TypedContractMethod<[], [bigint], "view">;

  multiply: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reset: TypedContractMethod<[], [void], "nonpayable">;

  setMaxCount: TypedContractMethod<
    [newMaxCount: BigNumberish],
    [void],
    "nonpayable"
  >;

  subtract: TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchAdd"
  ): TypedContractMethod<[values: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchSubtract"
  ): TypedContractMethod<[values: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "divide"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaxCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "multiply"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxCount"
  ): TypedContractMethod<[newMaxCount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subtract"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CountChanged"
  ): TypedContractEvent<
    CountChangedEvent.InputTuple,
    CountChangedEvent.OutputTuple,
    CountChangedEvent.OutputObject
  >;
  getEvent(
    key: "MaxCountUpdated"
  ): TypedContractEvent<
    MaxCountUpdatedEvent.InputTuple,
    MaxCountUpdatedEvent.OutputTuple,
    MaxCountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CountChanged(uint256,string,uint256)": TypedContractEvent<
      CountChangedEvent.InputTuple,
      CountChangedEvent.OutputTuple,
      CountChangedEvent.OutputObject
    >;
    CountChanged: TypedContractEvent<
      CountChangedEvent.InputTuple,
      CountChangedEvent.OutputTuple,
      CountChangedEvent.OutputObject
    >;

    "MaxCountUpdated(uint256)": TypedContractEvent<
      MaxCountUpdatedEvent.InputTuple,
      MaxCountUpdatedEvent.OutputTuple,
      MaxCountUpdatedEvent.OutputObject
    >;
    MaxCountUpdated: TypedContractEvent<
      MaxCountUpdatedEvent.InputTuple,
      MaxCountUpdatedEvent.OutputTuple,
      MaxCountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
