/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DelegationManager {
  export type TransactionStruct = {
    to: AddressLike;
    value: BigNumberish;
    data: BytesLike;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type TransactionStructOutput = [
    to: string,
    value: bigint,
    data: string,
    nonce: bigint,
    deadline: bigint
  ] & {
    to: string;
    value: bigint;
    data: string;
    nonce: bigint;
    deadline: bigint;
  };

  export type DelegationStruct = {
    delegator: AddressLike;
    delegate: AddressLike;
    expiresAt: BigNumberish;
    dailyLimit: BigNumberish;
    perTxLimit: BigNumberish;
    dailySpent: BigNumberish;
    lastResetDay: BigNumberish;
    isActive: boolean;
  };

  export type DelegationStructOutput = [
    delegator: string,
    delegate: string,
    expiresAt: bigint,
    dailyLimit: bigint,
    perTxLimit: bigint,
    dailySpent: bigint,
    lastResetDay: bigint,
    isActive: boolean
  ] & {
    delegator: string;
    delegate: string;
    expiresAt: bigint;
    dailyLimit: bigint;
    perTxLimit: bigint;
    dailySpent: bigint;
    lastResetDay: bigint;
    isActive: boolean;
  };
}

export interface DelegationManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DELEGATION_DURATION"
      | "MIN_DELEGATION_DURATION"
      | "canExecuteTransaction"
      | "createDelegation"
      | "delegations"
      | "emergencyWithdraw"
      | "executeTransaction"
      | "getDelegation"
      | "getUserDelegations"
      | "nextDelegationId"
      | "nonces"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeDelegation"
      | "transferOwnership"
      | "unpause"
      | "updateLimits"
      | "usedHashes"
      | "userDelegations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DelegationCreated"
      | "DelegationRevoked"
      | "LimitsUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "TransactionExecuted"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DELEGATION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DELEGATION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canExecuteTransaction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDelegation",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "delegations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish, DelegationManager.TransactionStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDelegations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDelegationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonces", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateLimits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDelegations",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DELEGATION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DELEGATION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canExecuteTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDelegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextDelegationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usedHashes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDelegations",
    data: BytesLike
  ): Result;
}

export namespace DelegationCreatedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegate: AddressLike,
    delegationId: BigNumberish,
    expiresAt: BigNumberish,
    dailyLimit: BigNumberish,
    perTxLimit: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegate: string,
    delegationId: bigint,
    expiresAt: bigint,
    dailyLimit: bigint,
    perTxLimit: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegate: string;
    delegationId: bigint;
    expiresAt: bigint;
    dailyLimit: bigint;
    perTxLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DelegationRevokedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegate: AddressLike,
    delegationId: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegate: string,
    delegationId: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegate: string;
    delegationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LimitsUpdatedEvent {
  export type InputTuple = [
    delegationId: BigNumberish,
    newDailyLimit: BigNumberish,
    newPerTxLimit: BigNumberish
  ];
  export type OutputTuple = [
    delegationId: bigint,
    newDailyLimit: bigint,
    newPerTxLimit: bigint
  ];
  export interface OutputObject {
    delegationId: bigint;
    newDailyLimit: bigint;
    newPerTxLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionExecutedEvent {
  export type InputTuple = [
    delegate: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    delegationId: BigNumberish
  ];
  export type OutputTuple = [
    delegate: string,
    to: string,
    value: bigint,
    data: string,
    delegationId: bigint
  ];
  export interface OutputObject {
    delegate: string;
    to: string;
    value: bigint;
    data: string;
    delegationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DelegationManager extends BaseContract {
  connect(runner?: ContractRunner | null): DelegationManager;
  waitForDeployment(): Promise<this>;

  interface: DelegationManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DELEGATION_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_DELEGATION_DURATION: TypedContractMethod<[], [bigint], "view">;

  canExecuteTransaction: TypedContractMethod<
    [delegationId: BigNumberish, value: BigNumberish],
    [[boolean, string] & { canExecute: boolean; reason: string }],
    "view"
  >;

  createDelegation: TypedContractMethod<
    [
      delegate: AddressLike,
      duration: BigNumberish,
      dailyLimit: BigNumberish,
      perTxLimit: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  delegations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        delegator: string;
        delegate: string;
        expiresAt: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        dailySpent: bigint;
        lastResetDay: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  executeTransaction: TypedContractMethod<
    [
      delegationId: BigNumberish,
      transaction: DelegationManager.TransactionStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDelegation: TypedContractMethod<
    [delegationId: BigNumberish],
    [DelegationManager.DelegationStructOutput],
    "view"
  >;

  getUserDelegations: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  nextDelegationId: TypedContractMethod<[], [bigint], "view">;

  nonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeDelegation: TypedContractMethod<
    [delegationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateLimits: TypedContractMethod<
    [
      delegationId: BigNumberish,
      newDailyLimit: BigNumberish,
      newPerTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  usedHashes: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  userDelegations: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DELEGATION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DELEGATION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canExecuteTransaction"
  ): TypedContractMethod<
    [delegationId: BigNumberish, value: BigNumberish],
    [[boolean, string] & { canExecute: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDelegation"
  ): TypedContractMethod<
    [
      delegate: AddressLike,
      duration: BigNumberish,
      dailyLimit: BigNumberish,
      perTxLimit: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        delegator: string;
        delegate: string;
        expiresAt: bigint;
        dailyLimit: bigint;
        perTxLimit: bigint;
        dailySpent: bigint;
        lastResetDay: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [
      delegationId: BigNumberish,
      transaction: DelegationManager.TransactionStruct,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDelegation"
  ): TypedContractMethod<
    [delegationId: BigNumberish],
    [DelegationManager.DelegationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDelegations"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextDelegationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeDelegation"
  ): TypedContractMethod<[delegationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLimits"
  ): TypedContractMethod<
    [
      delegationId: BigNumberish,
      newDailyLimit: BigNumberish,
      newPerTxLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "usedHashes"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "userDelegations"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "DelegationCreated"
  ): TypedContractEvent<
    DelegationCreatedEvent.InputTuple,
    DelegationCreatedEvent.OutputTuple,
    DelegationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DelegationRevoked"
  ): TypedContractEvent<
    DelegationRevokedEvent.InputTuple,
    DelegationRevokedEvent.OutputTuple,
    DelegationRevokedEvent.OutputObject
  >;
  getEvent(
    key: "LimitsUpdated"
  ): TypedContractEvent<
    LimitsUpdatedEvent.InputTuple,
    LimitsUpdatedEvent.OutputTuple,
    LimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionExecuted"
  ): TypedContractEvent<
    TransactionExecutedEvent.InputTuple,
    TransactionExecutedEvent.OutputTuple,
    TransactionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DelegationCreated(address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      DelegationCreatedEvent.InputTuple,
      DelegationCreatedEvent.OutputTuple,
      DelegationCreatedEvent.OutputObject
    >;
    DelegationCreated: TypedContractEvent<
      DelegationCreatedEvent.InputTuple,
      DelegationCreatedEvent.OutputTuple,
      DelegationCreatedEvent.OutputObject
    >;

    "DelegationRevoked(address,address,uint256)": TypedContractEvent<
      DelegationRevokedEvent.InputTuple,
      DelegationRevokedEvent.OutputTuple,
      DelegationRevokedEvent.OutputObject
    >;
    DelegationRevoked: TypedContractEvent<
      DelegationRevokedEvent.InputTuple,
      DelegationRevokedEvent.OutputTuple,
      DelegationRevokedEvent.OutputObject
    >;

    "LimitsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;
    LimitsUpdated: TypedContractEvent<
      LimitsUpdatedEvent.InputTuple,
      LimitsUpdatedEvent.OutputTuple,
      LimitsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TransactionExecuted(address,address,uint256,bytes,uint256)": TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;
    TransactionExecuted: TypedContractEvent<
      TransactionExecutedEvent.InputTuple,
      TransactionExecutedEvent.OutputTuple,
      TransactionExecutedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
